### ISSUE TITLE
[BUG] cluster error during predict with large raster stack

### ISSUE THREAD

**Issue by mrlewie** [ConsBiol-unibern/SDMtune#7] opened 2020-03-31 08:14 UTC
**Describe the bug**
Predict fails when using parallel = TRUE during a SDMtune::predict. Error message is:  
_in raster::clusterR(data, predict, args = list(model = model, clamp = clamp,  : 
  cluster error_

Raster stack being used is large, 14 layers each 9gb each. Doesn't appear to be a memory issue when observing windows task manager - plenty of memory left. 

If I turn parallel = FALSE, new error occurs:  
_in p[-naind, ] <- predv : "number of items to replace is not a multiple of replacement length"._

Reducing number of layers to less than 9 seems to fix it.

**Comment by sgvignali** [comment] 2020-03-31 08:47
Which version are you using?

Can you please post `sessionInfo()`

**Comment by mrlewie** [comment] 2020-03-31 09:03
Thanks, version 1.1.0

**Comment by sgvignali** [comment] 2020-03-31 09:11
In the next release I deprecated the use of parallel. This is because it improves only for very large datasets. The function used the cluster implemented by the package raster that uses the superseded package snow.
Despite that, your second error is strange, but I need more to figure it out, I should be able to reproduce it.
Maybe one of the layers has a problem, you could try to start with the 9 working layers and add the remaining one by one, to see which one causes the problem

**Comment by mrlewie** [comment] 2020-03-31 10:51
Thanks, i'll check my rasters.

**Comment by sgvignali** [comment] 2020-04-07 09:28
@mrlewie could you check your raster layers? If is not an issue related to the pkg we can close it!

**Closed** 2020-04-23 09:50 UTC
Labels: bug

**Comment by jennylinden** [comment] 2020-08-14 23:07
Hi, I see you've now closed this issue but I am having the same error with 13 raster layers. Did it turn out to be a problem with a raster? I know that can't be the case with mine because I've predicted with them all not in parallel, but am getting the same cluster error when trying it with clusterR.
